/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-12-20 16:42:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\" />\r\n");
      out.write("\r\n");
      out.write("    <title>MyDB - Custom database creator</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/maicons.css\" />\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/bootstrap.css\" />\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/vendor/animate/animate.css\" />\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/theme.css\" />\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/style.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- MyDB icon -->\r\n");
      out.write("    <link rel=\"icon\" href=\"./assets/images/cloud-data-300.png\">\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("    <!-- Back to top button -->\r\n");
      out.write("    <div class=\"back-to-top\"></div>\r\n");
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("      <!-- NAVBAR -->\r\n");
      out.write("      <nav class=\"navbar navbar-toggleable-md navbar-light bg-faded\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <a href=\"index.jsp\" class=\"navbar-brand\">My<span class=\"text-primary\">DB</span></a>\r\n");
      out.write("\r\n");
      out.write("          <button\r\n");
      out.write("            class=\"navbar-toggler navbar-toggler-right\"\r\n");
      out.write("            data-toggle=\"collapse\"\r\n");
      out.write("            type=\"button\" \r\n");
      out.write("            data-target=\"#navbarNav\" \r\n");
      out.write("            aria-controls=\"navbarNav\"\r\n");
      out.write("            aria-expanded=\"false\"\r\n");
      out.write("            aria-label=\"Toggle navigation\"\r\n");
      out.write("          >\r\n");
      out.write("            <span class=\"mai-person-outline\" id=\"nav-usr-icon\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"collapsed navbar-collapse collapse\" id=\"navbarNav\">\r\n");
      out.write("            <ul class=\"navbar-nav\">\r\n");
      out.write("              <li class=\"nav-item active\" id=\"nav-item-tr\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"index.jsp\">Home</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\" id=\"nav-item-tr\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"register.jsp\">Register</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\" id=\"nav-item-tr\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"login.jsp\">Login</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\" id=\"nav-item-tr\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"create.jsp\">Create table</a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("      <!-- NAVBAR -->\r\n");
      out.write("\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"page-banner home-banner\">\r\n");
      out.write("          <div class=\"row align-items-center flex-wrap-reverse h-100\">\r\n");
      out.write("            <div class=\"col-md-6 py-5 wow fadeInLeft\">\r\n");
      out.write("              <h1 class=\"mb-4\">\r\n");
      out.write("                An easy, fast and efficient way to create your own database.\r\n");
      out.write("              </h1>\r\n");
      out.write("              <p class=\"text-lg text-grey mb-5\">\r\n");
      out.write("                Get started by creating your first table!\r\n");
      out.write("              </p>\r\n");
      out.write("              <a href=\"create.jsp\" class=\"btn btn-primary btn-split\"\r\n");
      out.write("                >Create table\r\n");
      out.write("                <div class=\"fab\"><span class=\"mai-code\"></span></div\r\n");
      out.write("              ></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6 py-5 wow zoomIn\">\r\n");
      out.write("              <div class=\"img-fluid text-center\">\r\n");
      out.write("                <img src=\"./assets/images/cloud-data-300.png\" alt=\"cloud-data image\"/>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <a href=\"#about\" class=\"btn-scroll\" data-role=\"smoothscroll\"\r\n");
      out.write("            ><span class=\"mai-arrow-down\"></span\r\n");
      out.write("          ></a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- .container -->\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- .page-section -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Our service section -->\r\n");
      out.write("    <div class=\"page-section\" id=\"about\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row align-items-center\">\r\n");
      out.write("          <div class=\"col-lg-6 py-3 wow fadeInUp\">\r\n");
      out.write("            <span class=\"subhead\">Our Service</span>\r\n");
      out.write("            <h2 class=\"title-section\">The #1 creator of database tables</h2>\r\n");
      out.write("            <div class=\"divider\"></div>\r\n");
      out.write("\r\n");
      out.write("            <p>Expert or novice, we know how tedious it is to create a table using SQL code.</p>\r\n");
      out.write("            <p>That's why we invented My DataBase.</p>\r\n");
      out.write("            <p>MyDB is a completely free service to create and manage tables for your database.</p>\r\n");
      out.write("            <p>All without having to write a line of code!</p>\r\n");
      out.write("            <p>You only need to insert in a table the values you need and select the primary key, and you're done.</p>\r\n");
      out.write("            <p>Obviously you can customize the table with the number of rows and columns you need.</p>\r\n");
      out.write("            <p>Awesome, isn't it?</p>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-6 py-3 wow fadeInRight\">\r\n");
      out.write("            <div class=\"img-fluid py-3 text-center\">\r\n");
      out.write("              <img src=\"./assets/images/team-1-450.jpg\" alt=\"team-1 image\" />\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- .container -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- .page-section -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Our features section -->\r\n");
      out.write("    <div class=\"page-section bg-light\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"text-center wow fadeInUp\">\r\n");
      out.write("          <div class=\"subhead\">Our Features</div>\r\n");
      out.write("          <h2 class=\"title-section\">\r\n");
      out.write("            You can work without having an account, but registering provides you\r\n");
      out.write("            much more!\r\n");
      out.write("          </h2>\r\n");
      out.write("          <div class=\"divider mx-auto\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-sm-6 col-lg-4 col-xl-3 py-3 wow zoomIn\">\r\n");
      out.write("            <div class=\"features\">\r\n");
      out.write("              <div class=\"header mb-3\">\r\n");
      out.write("                <span class=\"mai-brush\"></span>\r\n");
      out.write("              </div>\r\n");
      out.write("              <h5>Create tables</h5>\r\n");
      out.write("              <p>Non-registered and Registered user</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-sm-6 col-lg-4 col-xl-3 py-3 wow zoomIn\">\r\n");
      out.write("            <div class=\"features\">\r\n");
      out.write("              <div class=\"header mb-3\">\r\n");
      out.write("                <span class=\"mai-cloud-download\"></span>\r\n");
      out.write("              </div>\r\n");
      out.write("              <h5>Export tables</h5>\r\n");
      out.write("              <p>Non-registered and Registered user</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-sm-6 col-lg-4 col-xl-3 py-3 wow zoomIn\">\r\n");
      out.write("            <div class=\"features\">\r\n");
      out.write("              <div class=\"header mb-3\">\r\n");
      out.write("                <span class=\"mai-cloud-done\"></span>\r\n");
      out.write("              </div>\r\n");
      out.write("              <h5>Save tables</h5>\r\n");
      out.write("              <p>Registered user only</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-sm-6 col-lg-4 col-xl-3 py-3 wow zoomIn\">\r\n");
      out.write("            <div class=\"features\">\r\n");
      out.write("              <div class=\"header mb-3\">\r\n");
      out.write("                <span class=\"mai-construct\"></span>\r\n");
      out.write("              </div>\r\n");
      out.write("              <h5>Manage tables</h5>\r\n");
      out.write("              <p>Registered user only</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- .container -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- .page-section -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Banner info -->\r\n");
      out.write("    <div class=\"page-section banner-info\">\r\n");
      out.write("      <div\r\n");
      out.write("        class=\"wrap bg-image\"\r\n");
      out.write("        style=\"background-image: url(./assets/images/bg_pattern.svg)\"\r\n");
      out.write("      >\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row align-items-center\">\r\n");
      out.write("            <div class=\"col-lg-6 py-3 pr-lg-5 wow fadeInUp\">\r\n");
      out.write("              <h2 class=\"title-section\">\r\n");
      out.write("                MyDB improves your experience with databases tables<br />\r\n");
      out.write("              </h2>\r\n");
      out.write("              <div class=\"divider\"></div>\r\n");
      out.write("              <p>\r\n");
      out.write("                MyDB was designed and created by GROUP 21 for the Servicios y Systemas Web course project in the year 2022. The course is provided by the Universidad de Valladolid.\r\n");
      out.write("              </p>\r\n");
      out.write("\r\n");
      out.write("              <ul class=\"theme-list theme-list-light text-white\">\r\n");
      out.write("                <li>\r\n");
      out.write("                  <div class=\"h5\">MyDB is a free service</div>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    Why free? Because we are engineering students and we like to make our knowledge available to others, hoping that someone will find our work useful.\r\n");
      out.write("                  </p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <div class=\"h5\">MyDB is developed by</div>\r\n");
      out.write("                  <p>\r\n");
      out.write("                    David Fernández García, Daniele Giorgianni, Paula Higuera Consuegra, Francisco Manzanas Mogrovejo\r\n");
      out.write("                  </p>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-6 py-3 wow fadeInRight\">\r\n");
      out.write("              <div class=\"img-fluid text-center\">\r\n");
      out.write("                <img src=\"./assets/images/banner_image_2.svg\" alt=\"banner image\" />\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- .wrap -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- .page-section -->\r\n");
      out.write("\r\n");
      out.write("    <!-- FOOTER -->\r\n");
      out.write("    <footer\r\n");
      out.write("      class=\"page-footer bg-image\"\r\n");
      out.write("      style=\"background-image: url(./assets/images/world_pattern.svg)\"\r\n");
      out.write("    >\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row mb-5\">\r\n");
      out.write("          <div class=\"col-lg-6 py-3\">\r\n");
      out.write("            <h3>MyDB</h3>\r\n");
      out.write("            <p>\r\n");
      out.write("              Follow us on our social channels.\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"social-media-button\">\r\n");
      out.write("              <a href=\"https://www.facebook.com/\"><span class=\"mai-logo-facebook-f\"></span></a>\r\n");
      out.write("              <a href=\"https://twitter.com/\"><span class=\"mai-logo-twitter\"></span></a>\r\n");
      out.write("              <a href=\"https://www.instagram.com/\"><span class=\"mai-logo-instagram\"></span></a>\r\n");
      out.write("              <a href=\"https://www.youtube.com/\"><span class=\"mai-logo-youtube\"></span></a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"col-lg-6 py-3\">\r\n");
      out.write("            <h5>Contact Us</h5>\r\n");
      out.write("            <p><a href=\"https://goo.gl/maps/Kr9kD6ZVdLPDxUTy8\" class=\"footer-link\">Inf-UVa, P.º de Belén, 15, 47011, Valladolid, Spain</a></p>\r\n");
      out.write("            <p><a href=\"tel:+34 123 45 67 89\" class=\"footer-link\">+34 123 45 67 89</a></p>\r\n");
      out.write("            <p><a href=\"mailto:mydb@fake.email.com\" class=\"footer-link\">mydb@fake.email.com</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- END FOOTER -->\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./assets/js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./assets/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./assets/vendor/wow/wow.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./assets/js/theme.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
